import React, { useState } from "react";
import { auth, db } from "../firebase";
import { useAuth } from "../contexts/AuthContext";
import { joinClassSectionTransaction } from "../lib/transactions";
import { Users, Layers, ShieldCheck, ArrowRight } from "lucide-react";

export default function JoinSection() {
  const { currentUser, userProfile, logout } = useAuth();
  const [joinCode, setJoinCode] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [successMsg, setSuccessMsg] = useState("");

  async function handleJoin(e) {
    e.preventDefault();
    if (joinCode.length !== 6) {
      return setError("Join code must be precisely 6 characters long.");
    }
    setError("");
    setLoading(true);
    
    try {
      const result = await joinClassSectionTransaction(currentUser.uid, joinCode.trim());
      setSuccessMsg(`Successfully joined ${result.assignedSection}! Your roll number is ${result.rollNumber}. Reloading dashboard...`);
      setTimeout(() => {
        window.location.reload();
      }, 2000);
    } catch (err) {
      console.error("Join Section Error:", err);
      setError(err.message || "Failed to join section. Please check the code.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center min-h-screen px-4 p-8 overflow-hidden auth-bg" style={{ background: "#06060c" }}>
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-indigo-600/10 rounded-full blur-[120px] pointer-events-none mix-blend-screen"></div>
      
      <div className="w-full max-w-[440px] relative z-10 animate-scale-in">
        <div className="flex flex-col items-center mb-8">
          <div className="w-16 h-16 rounded-2xl flex items-center justify-center mb-5 shadow-lg shadow-indigo-500/20 bg-gradient-to-br from-indigo-500 to-purple-600">
            <Users size={32} className="text-white" />
          </div>
          <h1 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-300">
            Join Your Class
          </h1>
          <p className="text-slate-400 text-[14px] mt-2 text-center max-w-sm">
            You require a 6-digit Join Code generated by your teacher to access your smart curriculum dashboard.
          </p>
        </div>

        <div className="p-8 rounded-3xl bg-[#0f0f1a]/80 backdrop-blur-2xl border border-white/[0.08] shadow-[0_8px_32px_rgba(0,0,0,0.5)] shadow-indigo-900/10">
          
          {(userProfile.registrationNumber) && (
            <div className="mb-6 px-4 py-3 bg-indigo-500/10 border border-indigo-500/20 rounded-xl flex items-center justify-between text-xs">
               <span className="text-slate-400 font-bold uppercase tracking-widest">Global ID</span>
               <span className="text-indigo-400 font-black font-mono">{userProfile.registrationNumber}</span>
            </div>
          )}

          {error && (
            <div className="mb-6 px-4 py-3 rounded-xl text-[13px] font-medium text-red-300 bg-red-500/10 border border-red-500/20 shadow-inner flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
              {error}
            </div>
          )}

          {successMsg && (
            <div className="mb-6 px-4 py-3 rounded-xl text-[13px] font-bold text-emerald-300 bg-emerald-500/10 border border-emerald-500/20 shadow-inner flex items-center gap-2">
              <ShieldCheck size={18} className="text-emerald-400"/>
              {successMsg}
            </div>
          )}

          <form onSubmit={handleJoin} className="space-y-6">
            <div>
              <label className="block text-[11px] font-bold text-slate-400 uppercase tracking-widest mb-2 ml-1">Join Code</label>
              <div className="relative group">
                <Layers size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400/80 pointer-events-none group-focus-within:text-purple-400 transition-colors duration-300" />
                <input
                  type="text"
                  required
                  value={joinCode}
                  onChange={e => setJoinCode(e.target.value.toUpperCase())}
                  placeholder="e.g. A1B2C3"
                  maxLength={6}
                  disabled={!!successMsg}
                  className="w-full bg-white/[0.03] border border-white/[0.08] rounded-xl text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/40 outline-none transition-all duration-300 p-4 pl-12 text-lg tracking-[0.2em] font-mono font-bold uppercase shadow-inner"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading || !!successMsg}
              className="w-full bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-bold py-4 rounded-xl shadow-[0_8px_20px_rgba(99,102,241,0.25)] transition-all duration-300 transform hover:-translate-y-0.5 flex items-center justify-center gap-2 disabled:opacity-50 disabled:hover:translate-y-0 text-sm tracking-widest uppercase"
            >
              {loading ? "Verifying..." : "Verify & Join"} 
              {!loading && <ArrowRight size={16} />}
            </button>
          </form>
          
          <button 
             onClick={() => logout()}
             className="w-full text-center mt-6 text-[11px] font-bold text-slate-500 uppercase tracking-widest hover:text-slate-300 transition-colors"
          >
             Sign out instead
          </button>
        </div>
      </div>
    </div>
  );
}
